services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: mssql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password.1234"
    ports:
      - "1433:1433"
  mytask-api:
    build: ./
    container_name: mytask-api
    environment:
      DatabaseServer: "mssql-server"
      DatabasePort: "1433"
      DatabaseUser: "sa"
      DatabasePassword: "Password.1234"
      DatabaseName: "MyTask_DB"
    depends_on:
      - mssql-server
    ports:
      - "8090:80"